---
ospf_process_id: "1"
router_id: "192.168.0.1"

ospf_vlans:
  - 101
  - 102
  - 103
  - 104
  - 105

configure_ospf:
  - name: Loopback0
    ipv4: "192.168.0.1/32"
    area: "0.0.0.0"
    passive: true

  - name: Vlan101
    ipv4: "172.16.101.2/24"
    area: "0.0.0.0"
    passive: false

  - name: Vlan102
    ipv4: "172.16.102.2/24"
    area: "0.0.0.0"
    passive: true

  - name: Vlan103
    ipv4: "172.16.103.2/24"
    area: "0.0.0.0"
    passive: true

  - name: Vlan104
    ipv4: "172.16.104.2/24"
    area: "0.0.0.0"
    passive: true

  - name: Vlan105
    ipv4: "172.16.105.2/24"
    area: "0.0.0.0"
    passive: true

  - name: Loopback100
    ipv4: "192.168.100.1/32"
    area: "0.0.0.0"
    passive: true